### ISSUE TITLE
서버 이전 안내(완료)

### ISSUE THREAD

**Issue by dhlife09** [dhlife09/Corona-19-API#11]
안녕하세요.

네이버 클라우드 플랫폼에서 서버를 지원받아 직접 호스팅중인 서버를 네이버 클라우드 플랫폼 서버로 이전할 예정입니다.

자세한 서버 이전 공지는 해당 게시글에 업데이트 될 예정이며 서버 이전 중 연결 및 서비스 불안정이 일시로 발생할 수 있습니다.

코로나19 극복을 위해 함께 힘써주시는 네이버 클라우드 플랫폼에게 감사드립니다!

[네이버 클라우드 플랫폼 바로가기](https://www.ncloud.com/)

![NaverCloudPlatform](https://user-images.githubusercontent.com/22024308/80802685-fce9a480-8bea-11ea-8b61-8a6b6c01eec4.png)

**Comment by dhlife09** [comment]
서비스 이전 작업이 2020.05.01 오후 7시경 완료되었습니다. 
API 서비스 정상 동작을 확인하였고 서버 이전으로 serviceKey 인증 시스템을 일시 중지하였습니다.

따라서 인증 없이도 API 서비스에 엑세스할 수 있으며 기존 API 키로 서비스에 엑세스 한 경우에도 그대로 서비스에 엑세스할 수 있습니다.

국내 발생동향 - http://api.corona-19.kr/korea
시도별 발생동향 - http://api.corona-19.kr/korea/country/new

감사합니다.

**Comment by wookho** [comment]
"updateTime": "코로나바이러스감염증-19 국내 발생현황",

업데이트 시간이 생략된 것 같은데 의도된 것인지 모르겠네요.

**Comment by dhlife09** [comment]
> "updateTime": "코로나바이러스감염증-19 국내 발생현황",
> 
> 업데이트 시간이 생략된 것 같은데 의도된 것인지 모르겠네요.

의도된 것이 아니며 질본 웹페이지 변경으로 추정됩니다. 점검 후 알려드리겠습니다.

**Comment by dhlife09** [comment]
> "updateTime": "코로나바이러스감염증-19 국내 발생현황",
> 
> 업데이트 시간이 생략된 것 같은데 의도된 것인지 모르겠네요.

확인 결과 질본 웹페이지 변경이 맞으며 다시 업데이트 되었습니다.
