### ISSUE TITLE
업데이트가 안되는 것 같습니다.

### ISSUE THREAD

**Issue by wookho** [dhlife09/Corona-19-API#12]
http://api.corona-19.kr/korea/country/new/

어제 데이터 그대로 같습니다.

**Comment by dhlife09** [comment]
특별한 오류가 감지된 적은 없습니다.

[질본에서 제공하는 페이지](http://ncov.mohw.go.kr/bdBoardList_Real.do?brdId=1&brdGubun=13&ncvContSeq=&contSeq=&board_id=&gubun=)가 업데이트되는 즉시 Corona-19-API에도 반영되니 참고 부탁드립니다.

추후에도 비슷한 오류가 발생한다면 질본 페이지 캡쳐본과 API 응답 스크린샷을 업로드해주시면 감사하겠습니다.
