### ISSUE TITLE
응답관련 건의사항

### ISSUE THREAD

**Issue by Muzihuzi** [dhlife09/Corona-19-API#17]
TotalCase 와 caseCount 는 항상 같은값을 반환하므로 하나는 없어도 상관없지 않을까요?

**Comment by dhlife09** [comment]
안녕하세요, 관심가져주셔서 감사합니다!
통합(변경)시 API 데이터에서 해당 항목들을 사용중인 타 프로그램에 문제가 발생할 수 있으므로 변경은 사실상 불가능 합니다.

publishing 전 개인적인 용도로 제작하여 어색한 이름도 있고 중복되는 값들이 있는 점 양해 부탁드립니다
