### ISSUE TITLE
API 속도개선, 이전 데이터 제공 안내

### ISSUE THREAD

**Issue by dhlife09** [dhlife09/Corona-19-API#19]
안녕하세요, 굿바이코로나 입니다.

/korea (1_국내카운터) API를 개선하여 공지드립니다.

기존에는 Request 마다 작업을 거쳐 JSON 데이터로 제공하였으나, 2020.11.22 이후 DB에 자동 저장되는 값을 이용해서 데이터를 제공하는 방식으로 변경되었습니다. (자동 저장되는 데이터는 오전 9:45분, 오전 11:45분. 이렇게 하루 두 번 동기화되며  **추가로 데이터가 동기화되지 않는 경우를 대비해, [홈페이지에서](https://api.corona-19.kr) 직접 데이터를 새로고침하실 수 있도록 제작 예정입니다.** )

방법 변경 전보다 변경한 후 받아오는 속도가 크게 줄었고 이전 데이터(20.11.15 이후) 제공이 곧 가능해질 예정입니다.

감사합니다.

---
**개선 전** 

![image](https://user-images.githubusercontent.com/22024308/99901408-e0819680-2cf9-11eb-98a3-6b674c3209fb.png)

---
**개선 후** 

![image](https://user-images.githubusercontent.com/22024308/99901418-e5dee100-2cf9-11eb-97af-17195c2ebca9.png)

**Comment by wookho** [comment]
9:45분, 오전 11:45분 두번 동기화 되는 바람에 지금 업데이트가 안되는데요. 
질병관리청에서 대략 9시20분 부터 업데이트가 되는 경우가 많고 늦어지는 경우는 9:45분이 넘어서 업데이트가 되는 경우가 많이 있습니다.

업데이트 간격을 조금 촘촘하게 여러번 해줘야 할 것 같은데요.
