### ISSUE TITLE
국내 정보 업데이 확인 간격을 조금 더 촘촘히 부탁드립니다.

### ISSUE THREAD

**Issue by wookho** [dhlife09/Corona-19-API#20]
https://github.com/dhlife09/Corona-19-API/issues/19#issuecomment-733403121

댓글로 남겨드렸는데요.

질병청에서 9시 20분 경부터 업데이트가 될 때가 있고 때로는 지체되서 9시 50분 10시 이렇게까지 늦어지는 경우도 흔하게 있습니다.

그런데 지금 매번 확인에서 9시 45분, 11시 45분 두번 확인하는 거로 바뀐 후 자칫 9시 50분 ~ 11시 45 분까지 업데이된 것이 확인이 안되는 경우가 발생합니ㅏ. 

새로운 정보를 정오나 되어서야 확인이 되는 상황이 발생하는 건데요.

적어도 9시 45분 이후 15분 정도의 간격으로 확인이 필요해 보입니다.

**Comment by dhlife09** [comment]
답글이 올라가지 않았네요. 어제 기존 시간에 추가로 15분-20분 등 간격으로 추가를 완료했습니다.

오늘은 2020/11/26 09:45:07 정상적으로 처리가 되었습니다.

오늘 확인했을때도 9시 45분에 업데이트가 되었습니다.


데이터가 즉시 반영되시지 않으신다면 사용하시는 프로그램에서의 점검이 필요하다고 생각됩니다.

**Comment by wookho** [comment]
@dhlife09 아니요. 오늘은 오래 업데이트가 안되는 상황이 연출되지는 않았습니다. 어제 의견에 답이 없으셔서 못보신 줄 알고 이슈로 등록했습니다. 반영해주셔서 감사합니다.
앞으로 질병청에서 9시 45 이후에 업데이트 되었을 경우가 우려되서 이슈로 등록한건데요. 15~ 20분 간격으로 확인하도록 해주셨으니 이제 걱정 없겠네요.
감사합니다.
