### ISSUE TITLE
질병청 홈페이지가 가끔 오후에나 업데이트가 되는 경우가 있습니다.

### ISSUE THREAD

**Issue by wookho** [dhlife09/Corona-19-API#21]
오늘이 그런 날인데요. 내부적인 문제일 텐데 월요일 이런 일이 자주 일어나는 듯 합니다.
질병청에서 너무 늦게 업데이트 하는 바람에 저희 api에서 확인하는 시간이 지나가 버렸습니다.

일단 이런 문제가 일어난 다는 것을 이슈로 등록해 봅니다.

**Comment by dhlife09** [comment]
확인하였습니다
제보해주셔서 감사합니다.. ㅠㅠ

14:37:06 확인 즉시 데이터 반영을 완료했습니다.

최소 매 시간에 1번정도는 체크하는 방향을 생각해 보는게 좋겠네요

**Comment by wookho** [comment]
@dhlife09 네. 오후 3시를 넘기는 경우는 없는 거 같으니... 9시45분 부터 13시 까지는 조금 촘촘하게 이후는 대략 1시간 정도로 혹시 모를 확인을 해야 할 것 같습니다.
