### ISSUE TITLE
blocked by CORS policy

### ISSUE THREAD

**Issue by jiingler** [dhlife09/Corona-19-API#27]
Access to fetch at 'https://api.corona-19.kr/korea/country/new/?serviceKey=*' from origin 'my own domain' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

CORS 문제를 어떻게 해결해야 할까요?

**Comment by dhlife09** [comment]
API 키 노출 주의해주세요.
dhlife09@gmail.com 로 연락주시면 도와드리겠습니다.
