### ISSUE TITLE
코로나 API 시도별 발생현황에 오류가 있는 것 같습니다

### ISSUE THREAD

**Issue by cjh980402** [dhlife09/Corona-19-API#29]
https://corona-19.kr/ 이 사이트에서 확인해도 마찬가지고
api 호출해서 받아온 내용도 마찬가지로 대구의 비율이 실제와 달리 엄청 높게 뜨는 등의 수치 오류가 있는 것 같습니다.

**Comment by cjh980402** [comment]
API의 수치 (https://corona-19.kr/)
 대구 65.31%
 경북 12.66%
 기타 10.54%
 경기 5.81%
 서울 5.66%

실제 수치 (http://ncov.mohw.go.kr/bdBoardList_Real.do?brdId=1&brdGubun=11&ncvContSeq=&contSeq=&board_id=&gubun=)
서울 31.5%
기타 27.8%
경기 26.0%
대구 9.8%
인천 4.9%

**Comment by dhlife09** [comment]
긴급하게 확인 후 수정하였습니다. 제보해주셔서 감사합니다

**Comment by dhlife09** [comment]
{
    "resultCode": "0",
    "TotalCase": "87,324",
    "TotalRecovered": "77,887",
    "TotalDeath": "1,562",
    "NowCase": "7,875",
    "city1n": "서울",
    "city2n": "기타",
    "city3n": "경기",
    "city4n": "대구",
    "city5n": "인천",
    "city1p": "31.5",
    "city2p": "27.8",
    "city3p": "26",
    "city4p": "9.8",
    "city5p": "4.9",
    "recoveredPercentage": 89.19,
    "deathPercentage": 1.79,
    "checkingCounter": "72,461",
    "checkingPercentage": "1.1",
    "caseCount": "87,324",
    "casePercentage": "1.4",
    "notcaseCount": "6,269,359",
    "notcasePercentage": "97.5",
    "TotalChecking": "6,429,144",
    "TodayRecovered": "371",
    "TodayDeath": "5",
    "TotalCaseBefore": "-44",
    "source": "GOODBYE_CORONA",
    "updateTime": "코로나바이러스감염증-19 국내 발생현황 (2.22. 00시 기준)",
    "resultMessage": "정상 처리되었습니다."
}

데이터 수정이 완료되었습니다. 원인을 찾아보고 있습니다.

**Comment by cjh980402** [comment]
넵 감사합니다 ㅎㅎ
