### ISSUE TITLE
이미지 표기 관련 이슈

### ISSUE THREAD

**Issue by KimJei** [dhlife09/Corona-19-API#30]
TotalCaseBefore , TodayRecoverd 관련 이미지 표기가 잘못되었습니다.

**Comment by dhlife09** [comment]
무슨 이미지 말씀이신가요?

**Comment by KimJei** [comment]
https://user-images.githubusercontent.com/22024308/106720839-4c13a880-6647-11eb-9b77-0edc84e28886.jpg

해당 이미지 입니다 :)
