### ISSUE TITLE
서비스 복구가 완료되었습니다.

### ISSUE THREAD

**Issue by dhlife09** [dhlife09/Corona-19-API#31]
**[Corona-19-API] 서비스 복구가 완료되었습니다. 현재는 정상 작동하며 기다려주셔서 감사합니다. 서비스 이용에 불편을 드려 죄송합니다.**

---

[Corona-19-API] 임시 복구되어 점검 예정입니다. 점검중에도 서비스 이용이 가능하니 참고부탁드립니다.

---
안녕하세요, 굿바이코로나 입니다.

인터넷서비스사업자로부터 긴급 시설점검 안내를 받고 오전 4시 38분부터 지금까지 접속이 안되고 있습니다.
(IP를 받아오지 못하고 있는 상황입니다.)

서버에서는 현재 복구 시 바로 IP가 설정되어 서비스 접근이 가능하도록 설정되었으며, 그 전까지는 접속이 불가할 것으로 예상됩니다.

* 영향을 받는 서비스
 굿바이코로나, Corona-19-API 등

최대한 빠르게 인터넷사업자 측에 연락해 빠른 해결이 가능하도록 노력하겠습니다.

불편을 드려 죄송합니다.

아래는 메시지 전문입니다.

```
[***] 자체 시설점검으로 서비스 이용에 일시적 불편을 드려 죄송합니다
 
고객님, 3월 31일(수) 오전 03시~06시까지 고객님께서 거주하시는 ***의 통신시설 긴급 보수로 인해 일시적으로 인터넷, TV 등의 서비스 이용이 어려울 수 있습니다. 고객님의 양해 부탁드립니다.
 
[문의] 고객센터 ***
```

---

**Comment by C17AN** [comment]
아구구 갑자기 데이터가 나오지 않아서 깜짝 놀랐네요!!
이슈로 남겨주시지 않았더라면 많이 당황했을텐데, 이렇게 공지로 알려주셔서 감사드립니다!

빨리 복구되길 바라며... 좋은 서비스 제공해주셔서 감사드립니다!

**Comment by dhlife09** [comment]
[Corona-19-API] 임시 복구되어 점검 예정입니다. 점검중에도 서비스 이용이 가능하니 참고부탁드립니다.
