### ISSUE TITLE
서버 장애가 있는 것 같습니다.

### ISSUE THREAD

**Issue by wookho** [dhlife09/Corona-19-API#36]
api, https://corona-19.kr/ 두곳 모두 접속이 안되고 있네요.

**Comment by dhlife09** [comment]
남겨주셔서 감사합니다. 확인중입니다

**Comment by dhlife09** [comment]
해결되었습니다. 불편을 드려 죄송합니다

**Comment by dhlife09** [comment]
시도별 발생동향 API에 문제가 발생하였습니다. 해결 후 다시 안내드리겠습니다
