### ISSUE TITLE
데이터가 정상적이지 않네요.

### ISSUE THREAD

**Issue by wookho** [dhlife09/Corona-19-API#40]
질병청 홈페이지는 7월 10일 갱신이 되었는데
api는 7월 9일 날짜이면서 데이터는 비정상 데이터 입니다.

국내 확진자 숫자가 39명으로 나오고 있습니다.

http://ncov.mohw.go.kr/bdBoardList_Real.do?brdId=1&brdGubun=11&ncvContSeq=&contSeq=&board_id=&gubun=

여기 데이터가 비정상이군요.

**Comment by dhlife09** [comment]
![Screenshot_20210710-110107_Samsung Internet.jpg](https://user-images.githubusercontent.com/22024308/125148569-3c583d00-e16e-11eb-92a9-4df75f26119e.jpg)

넵.. 시도별 발생동향 페이지의 정보오류로 인해 발생하고 있습니다.

수정하도록 하겠습니다 감사합니다

**Comment by dhlife09** [comment]
수정 완료되었습니다.
https://github.com/dhlife09/Corona-19-API/issues/41
