### ISSUE TITLE
국내 시도별 데이터 문의 드립니다.

### ISSUE THREAD

**Issue by wookho** [dhlife09/Corona-19-API#42]
https://github.com/dhlife09/Corona-19-API/issues/41#issuecomment-877558476

위 코멘트에 의하면 

https://api.corona-19.kr/korea/country/new 
데이터를 사용해야 할 것 같은데(저는 이 데이터를 계속 사용했습니다.) 
그런데 오늘 데이터가 어제 데이터로 제공되고 있음이 확인됩니다.

https://api.corona-19.kr/korea/ 의 데이터가 갱신된 데이터로 제공이 됩니다. 

어떤 데이터를 사용해야 하는 것인가요???

**Comment by dhlife09** [comment]
수정되었습니다. 어제 발생했던 데이터 오류건으로 인해 발생했던 사항입니다. 

감사합니다
