### ISSUE TITLE
서버 장애 이슈

### ISSUE THREAD

**Issue by toriving** [dhlife09/Corona-19-API#46]
안녕하세요. 
좋은 API를 만들어주셔서 유용하게 잘 사용하고 있습니다.
어제 (8월 1일) 부터 해서 API 요청시 종종 장애가 있는것 같은데 확인 부탁드립니다.
감사합니다.

**Comment by dhlife09** [comment]
안녕하세요, 발생하는 오류의 내용을 알 수 있을까요? 
API 내에서 오류 메시지가 출력되거나 HTTP 코드를 알려주시면 확인해 보겠습니다.

**Comment by toriving** [comment]
간헐적으로 500 error가 발생합니다.

**Comment by dhlife09** [comment]
https://github.com/dhlife09/Corona-19-API/issues/47#issuecomment-891202229

해당 사안에 대해 인지하였으며, 위의 게시글 확인부탁드립니다.

제보해주셔서 감사합니다
