### ISSUE TITLE
국내 정보가 어제 데이터에서 갱신이 안되고 있습니다.

### ISSUE THREAD

**Issue by wookho** [dhlife09/Corona-19-API#48]
https://api.corona-19.kr/korea/country/new/

현재 어제 데이터로 계속 제공되고 있습니다.

{
   "resultCode":"0",
   "resultMessage":"정상 처리되었습니다.",
   "korea":{
      "countryName":"합계",
      "newCase":"1,200",
      "totalCase":"202,201",
      "recovered":"177,911",
      "death":"2,104",
      "percentage":"390.13",
      "newCcase":"1,150",
      "newFcase":"50"
   },
   "seoul":{
      "countryName":"서울",
      "newCase":"311",
      "totalCase":"65,503",
      "recovered":"56,803",
      "death":"537",
      "percentage":"677.49",
      "newCcase":"307",
      "newFcase":"4"
   },
   "busan":{
      "countryName":"부산",
      "newCase":"69",
      "totalCase":"8,405",
      "recovered":"7,313",
      "death":"128",
      "percentage":"247.79",
      "newCcase":"67",
      "newFcase":"2"
   },
   "daegu":{
      "countryName":"대구",
      "newCase":"37",
      "totalCase":"11,755",
      "recovered":"10,989",
      "death":"222",
      "percentage":"486.08",
      "newCcase":"37",
      "newFcase":"0"
   },
   "incheon":{
      "countryName":"인천",
      "newCase":"48",
      "totalCase":"9,288",
      "recovered":"8,045",
      "death":"65",
      "percentage":"315.61",
      "newCcase":"46",
      "newFcase":"2"
   },
   "gwangju":{
      "countryName":"광주",
      "newCase":"18",
      "totalCase":"3,448",
      "recovered":"3,203",
      "death":"24",
      "percentage":"237.78",
      "newCcase":"17",
      "newFcase":"1"
   },
   "daejeon":{
      "countryName":"대전",
      "newCase":"78",
      "totalCase":"4,400",
      "recovered":"3,284",
      "death":"30",
      "percentage":"300.57",
      "newCcase":"78",
      "newFcase":"0"
   },
   "ulsan":{
      "countryName":"울산",
      "newCase":"8",
      "totalCase":"3,247",
      "recovered":"3,061",
      "death":"41",
      "percentage":"285.82",
      "newCcase":"8",
      "newFcase":"0"
   },
   "sejong":{
      "countryName":"세종",
      "newCase":"7",
      "totalCase":"755",
      "recovered":"674",
      "death":"1",
      "percentage":"212.18",
      "newCcase":"6",
      "newFcase":"1"
   },
   "gyeonggi":{
      "countryName":"경기",
      "newCase":"360",
      "totalCase":"56,884",
      "recovered":"50,283",
      "death":"684",
      "percentage":"423.65",
      "newCcase":"344",
      "newFcase":"16"
   },
   "gangwon":{
      "countryName":"강원",
      "newCase":"25",
      "totalCase":"4,587",
      "recovered":"4,051",
      "death":"56",
      "percentage":"297.31",
      "newCcase":"21",
      "newFcase":"4"
   },
   "chungbuk":{
      "countryName":"충북",
      "newCase":"39",
      "totalCase":"3,932",
      "recovered":"3,521",
      "death":"71",
      "percentage":"245.62",
      "newCcase":"38",
      "newFcase":"1"
   },
   "chungnam":{
      "countryName":"충남",
      "newCase":"51",
      "totalCase":"5,081",
      "recovered":"4,426",
      "death":"45",
      "percentage":"239.65",
      "newCcase":"49",
      "newFcase":"2"
   },
   "jeonbuk":{
      "countryName":"전북",
      "newCase":"16",
      "totalCase":"2,810",
      "recovered":"2,508",
      "death":"60",
      "percentage":"155.76",
      "newCcase":"16",
      "newFcase":"0"
   },
   "jeonnam":{
      "countryName":"전남",
      "newCase":"4",
      "totalCase":"2,054",
      "recovered":"1,836",
      "death":"17",
      "percentage":"110.93",
      "newCcase":"4",
      "newFcase":"0"
   },
   "gyeongbuk":{
      "countryName":"경북",
      "newCase":"25",
      "totalCase":"5,540",
      "recovered":"5,144",
      "death":"87",
      "percentage":"209.89",
      "newCcase":"22",
      "newFcase":"3"
   },
   "gyeongnam":{
      "countryName":"경남",
      "newCase":"72",
      "totalCase":"7,444",
      "recovered":"6,355",
      "death":"23",
      "percentage":"222.86",
      "newCcase":"70",
      "newFcase":"2"
   },
   "jeju":{
      "countryName":"제주",
      "newCase":"21",
      "totalCase":"1,785",
      "recovered":"1,588",
      "death":"1",
      "percentage":"264.59",
      "newCcase":"20",
      "newFcase":"1"
   },
   "quarantine":{
      "countryName":"검역",
      "newCase":"11",
      "totalCase":"5,283",
      "recovered":"4,827",
      "death":"12",
      "percentage":"-",
      "newCcase":"0",
      "newFcase":"11"
   }
}

**Comment by gurum77** [comment]
그러네요. 지금 되네요.

**Comment by dhlife09** [comment]
제보해주셔서 감사합니다. 학교에 있어서 코멘트 작성이 늦었습니다.

해당 이슈 확인 후 즉시 수동 업데이트 하였습니다.

시간이 날 때마다 비효율적이던 기존 구조를 바꾸고 데이터 검증 및 오류대비 작업을 하고 있습니다. 다만 시간은 조금 걸릴것으로 생각됩니다..

빠른 시일 내 안정적인 서비스가 가능하도록 노력하겠습니다
