### ISSUE TITLE
데이터 갱신이 되었으면 좋겠습니다.

### ISSUE THREAD

**Issue by wookho** [dhlife09/Corona-19-API#57]
신규 데이터 확인 주기 시간이 긴 것인지 질병청 데이터 업데이트 후 api 데이터 갱신 시점 차이가 제법 납니다.
오늘 데이터 갱신도 지금 되면 좋겠습니다.

**Comment by dhlife09** [comment]
안녕하세요, 사이트 변경으로 오류가 발생해 업데이트가 지연되고 있습니다.

최대한 빨리 해결 및 신버전 업데이트 하도록 하겠습니다. 불편을 드려 죄송합니다
