### ISSUE TITLE
강원지역 응답 변수에 0이 있어서 500에러가 발생합니다.

### ISSUE THREAD

**Issue by wookho** [dhlife09/Corona-19-API#6]
"0newCase": "1",
        "0totalCase": "52",
        "0recovered": "27",
        "0death": "1",
        "0percentage": "3.38",
        "0newFcase": "0",
        "0newCcase": "1"

다른 지역은 출력을 잘 했는데 강원 지역의 0이 붙은 항목은 출력하려면 500에러가 납니다.

**Comment by dhlife09** [comment]
처리되었습니다. 감사합니다.
