### ISSUE TITLE
혹시나 해서 등록해 봅니다.

### ISSUE THREAD

**Issue by wookho** [dhlife09/Corona-19-API#7]
https://github.com/dhlife09/Corona-19-API/blob/master/README.md#-1-1-%EA%B5%AD%EB%82%B4-%EC%B9%B4%EC%9A%B4%ED%84%B0

국내정보에서 
오늘 사망자 수 가 제공되면 좋을 것 같은데요. 혹시 가능할까요??

TodayDeath 정도 될 것 같습니다. 

요거 하나만 없는 거 같더라구요.

지역별 오늘 사망자는 필요 없을 것 같구요.

**Comment by dhlife09** [comment]
제안해주셔서 감사합니다. 국내 카운터 API(api.corona-19.kr/korea)에 추가되었습니다.

TodayDeath: 오늘 사망자 수
TotalCaseBefore: 전날대비 치료중인 환자 수
