### ISSUE TITLE
더 이상 서비스 지원 안하나요?

### ISSUE THREAD

**Issue by Pma10** [dhlife09/Corona-19-API#79]
2023년 8월 2일이 마지막 갱신이네요

**Comment by dhlife09** [comment]
안녕하세요.

결론부터 말씀드리자면 신규 업데이트 및 데이터 업데이트 예정은 아직 없음을 알려드립니다.

1. 현재 코로나19 상황이 많이 호전되었고, 사회적인 관심도도 많이 낮아진 상태입니다.

2. 현재 개인적으로 하고 있는 개발/정보보안 공부, 자격증 취득, 군입대 준비 등 바빠서 유지보수 및 업데이트 하기 어려운 점도 있습니다.

3. 가끔 해당 API를 사용한 개발 공부 등 목적은 계속 확인되고 있어(공공,교육기관 등), API 자체는 일단 유지하고 있습니다.


감사합니다.

**Comment by Pma10** [comment]
아, 그렇군요.. 감사합니다
